version: '3'

services:
  db:
    image: postgres:9-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: backend-lab
  app:
    image: backend-lab
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 7070
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/backend-lab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "7070:7070"
