version: '3'

services:
  app:
    image: backend-lab2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 7070
    ports:
      - "7070:7070"
